package com.matez.wildnature.registry;

import com.matez.wildnature.Main;
import com.matez.wildnature.blocks.*;
import com.matez.wildnature.lists.WNBlocks;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.PressurePlateBlock;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;

public class BuildingRegistry {

    public Block[] rocks;

    public BuildingRegistry(){
        rocks = new Block[]{
                WNBlocks.BASALT_COBBLE = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_cobble")),
                WNBlocks.CONGLOMERATE_COBBLE = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_cobble")),
                WNBlocks.GNEISS_COBBLE = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_cobble")),
                WNBlocks.LIMESTONE_COBBLE = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_cobble")),
                WNBlocks.MARBLE_COBBLE = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_cobble")),
                WNBlocks.PEGMATITE_COBBLE = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_cobble")),
                WNBlocks.SLATE_COBBLE= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_cobble")),


                WNBlocks.BASALT_COBBLE_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_cobble_mossy")),
                WNBlocks.CONGLOMERATE_COBBLE_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_cobble_mossy")),
                WNBlocks.GNEISS_COBBLE_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_cobble_mossy")),
                WNBlocks.LIMESTONE_COBBLE_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_cobble_mossy")),
                WNBlocks.MARBLE_COBBLE_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_cobble_mossy")),
                WNBlocks.PEGMATITE_COBBLE_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_cobble_mossy")),
                WNBlocks.SLATE_COBBLE_MOSSY= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_cobble_mossy")),

                WNBlocks.BASALT_POLISHED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_polished")),
                WNBlocks.CONGLOMERATE_POLISHED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_polished")),
                WNBlocks.GNEISS_POLISHED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_polished")),
                WNBlocks.LIMESTONE_POLISHED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_polished")),
                WNBlocks.MARBLE_POLISHED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_polished")),
                WNBlocks.PEGMATITE_POLISHED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_polished")),
                WNBlocks.SLATE_POLISHED= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_polished")),

                WNBlocks.BASALT_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_bricks")),
                WNBlocks.CONGLOMERATE_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_bricks")),
                WNBlocks.GNEISS_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_bricks")),
                WNBlocks.LIMESTONE_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_bricks")),
                WNBlocks.MARBLE_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_bricks")),
                WNBlocks.PEGMATITE_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_bricks")),
                WNBlocks.SLATE_BRICKS= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_bricks")),

                WNBlocks.BASALT_BRICKS_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_bricks_mossy")),
                WNBlocks.CONGLOMERATE_BRICKS_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_bricks_mossy")),
                WNBlocks.GNEISS_BRICKS_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_bricks_mossy")),
                WNBlocks.LIMESTONE_BRICKS_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_bricks_mossy")),
                WNBlocks.MARBLE_BRICKS_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_bricks_mossy")),
                WNBlocks.PEGMATITE_BRICKS_MOSSY = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_bricks_mossy")),
                WNBlocks.SLATE_BRICKS_MOSSY= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_bricks_mossy")),

                WNBlocks.BASALT_BRICKS_CHISELED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_bricks_chiseled")),
                WNBlocks.CONGLOMERATE_BRICKS_CHISELED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_bricks_chiseled")),
                WNBlocks.GNEISS_BRICKS_CHISELED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_bricks_chiseled")),
                WNBlocks.LIMESTONE_BRICKS_CHISELED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_bricks_chiseled")),
                WNBlocks.MARBLE_BRICKS_CHISELED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_bricks_chiseled")),
                WNBlocks.PEGMATITE_BRICKS_CHISELED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_bricks_chiseled")),
                WNBlocks.SLATE_BRICKS_CHISELED= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_bricks_chiseled")),

                WNBlocks.BASALT_BRICKS_CRACKED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_bricks_cracked")),
                WNBlocks.CONGLOMERATE_BRICKS_CRACKED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_bricks_cracked")),
                WNBlocks.GNEISS_BRICKS_CRACKED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_bricks_cracked")),
                WNBlocks.LIMESTONE_BRICKS_CRACKED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_bricks_cracked")),
                WNBlocks.MARBLE_BRICKS_CRACKED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_bricks_cracked")),
                WNBlocks.PEGMATITE_BRICKS_CRACKED = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_bricks_cracked")),
                WNBlocks.SLATE_BRICKS_CRACKED= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_bricks_cracked")),

                WNBlocks.BASALT_SMALL_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_small_bricks")),
                WNBlocks.CONGLOMERATE_SMALL_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_small_bricks")),
                WNBlocks.GNEISS_SMALL_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_small_bricks")),
                WNBlocks.LIMESTONE_SMALL_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_small_bricks")),
                WNBlocks.MARBLE_SMALL_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_small_bricks")),
                WNBlocks.PEGMATITE_SMALL_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_small_bricks")),
                WNBlocks.SLATE_SMALL_BRICKS= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_small_bricks")),

                WNBlocks.BASALT_LONG_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_long_bricks")),
                WNBlocks.CONGLOMERATE_LONG_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_long_bricks")),
                WNBlocks.GNEISS_LONG_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_long_bricks")),
                WNBlocks.LIMESTONE_LONG_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_long_bricks")),
                WNBlocks.MARBLE_LONG_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_long_bricks")),
                WNBlocks.PEGMATITE_LONG_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_long_bricks")),
                WNBlocks.SLATE_LONG_BRICKS= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_long_bricks")),

                WNBlocks.BASALT_ANCIENT_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_ancient_bricks")),
                WNBlocks.CONGLOMERATE_ANCIENT_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_ancient_bricks")),
                WNBlocks.GNEISS_ANCIENT_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_ancient_bricks")),
                WNBlocks.LIMESTONE_ANCIENT_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_ancient_bricks")),
                WNBlocks.MARBLE_ANCIENT_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_ancient_bricks")),
                WNBlocks.PEGMATITE_ANCIENT_BRICKS = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_ancient_bricks")),
                WNBlocks.SLATE_ANCIENT_BRICKS= new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_ancient_bricks")),

                WNBlocks.BASALT_PILLAR = new PillarBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_pillar")),
                WNBlocks.CONGLOMERATE_PILLAR = new PillarBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_pillar")),
                WNBlocks.GNEISS_PILLAR = new PillarBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_pillar")),
                WNBlocks.LIMESTONE_PILLAR = new PillarBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_pillar")),
                WNBlocks.MARBLE_PILLAR = new PillarBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_pillar")),
                WNBlocks.PEGMATITE_PILLAR = new PillarBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_pillar")),
                WNBlocks.SLATE_PILLAR= new PillarBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_pillar")),

                WNBlocks.BASALT_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_slab")),
                WNBlocks.CONGLOMERATE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_slab")),
                WNBlocks.GNEISS_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_slab")),
                WNBlocks.LIMESTONE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_slab")),
                WNBlocks.MARBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_slab")),
                WNBlocks.PEGMATITE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_slab")),
                WNBlocks.SLATE_SLAB= new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_slab")),

                WNBlocks.BASALT_POLISHED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_polished_slab")),
                WNBlocks.CONGLOMERATE_POLISHED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_polished_slab")),
                WNBlocks.GNEISS_POLISHED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_polished_slab")),
                WNBlocks.LIMESTONE_POLISHED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_polished_slab")),
                WNBlocks.MARBLE_POLISHED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_polished_slab")),
                WNBlocks.PEGMATITE_POLISHED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_polished_slab")),
                WNBlocks.SLATE_POLISHED_SLAB= new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_polished_slab")),

                WNBlocks.BASALT_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_slab_cobble")),
                WNBlocks.CONGLOMERATE_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_slab_cobble")),
                WNBlocks.GNEISS_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_slab_cobble")),
                WNBlocks.LIMESTONE_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_slab_cobble")),
                WNBlocks.MARBLE_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_slab_cobble")),
                WNBlocks.PEGMATITE_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_slab_cobble")),
                WNBlocks.SLATE_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_slab_cobble")),

                WNBlocks.BASALT_MOSSY_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_slab_cobble_mossy")),
                WNBlocks.CONGLOMERATE_MOSSY_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_slab_cobble_mossy")),
                WNBlocks.GNEISS_MOSSY_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_slab_cobble_mossy")),
                WNBlocks.LIMESTONE_MOSSY_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_slab_cobble_mossy")),
                WNBlocks.MARBLE_MOSSY_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_slab_cobble_mossy")),
                WNBlocks.PEGMATITE_MOSSY_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_slab_cobble_mossy")),
                WNBlocks.SLATE_MOSSY_COBBLE_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_slab_cobble_mossy")),

                WNBlocks.BASALT_BRICKS_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_slab_bricks")),
                WNBlocks.CONGLOMERATE_BRICKS_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_slab_bricks")),
                WNBlocks.GNEISS_BRICKS_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_slab_bricks")),
                WNBlocks.LIMESTONE_BRICKS_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_slab_bricks")),
                WNBlocks.MARBLE_BRICKS_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_slab_bricks")),
                WNBlocks.PEGMATITE_BRICKS_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_slab_bricks")),
                WNBlocks.SLATE_BRICKS_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_slab_bricks")),

                WNBlocks.BASALT_BRICKS_MOSSY_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_slab_bricks_mossy")),
                WNBlocks.CONGLOMERATE_BRICKS_MOSSY_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_slab_bricks_mossy")),
                WNBlocks.GNEISS_BRICKS_MOSSY_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_slab_bricks_mossy")),
                WNBlocks.LIMESTONE_BRICKS_MOSSY_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_slab_bricks_mossy")),
                WNBlocks.MARBLE_BRICKS_MOSSY_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_slab_bricks_mossy")),
                WNBlocks.PEGMATITE_BRICKS_MOSSY_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_slab_bricks_mossy")),
                WNBlocks.SLATE_BRICKS_MOSSY_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_slab_bricks_mossy")),

                WNBlocks.BASALT_BRICKS_CHISELED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_slab_bricks_chiseled")),
                WNBlocks.CONGLOMERATE_BRICKS_CHISELED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_slab_bricks_chiseled")),
                WNBlocks.GNEISS_BRICKS_CHISELED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_slab_bricks_chiseled")),
                WNBlocks.LIMESTONE_BRICKS_CHISELED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_slab_bricks_chiseled")),
                WNBlocks.MARBLE_BRICKS_CHISELED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_slab_bricks_chiseled")),
                WNBlocks.PEGMATITE_BRICKS_CHISELED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_slab_bricks_chiseled")),
                WNBlocks.SLATE_BRICKS_CHISELED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_slab_bricks_chiseled")),

                WNBlocks.BASALT_BRICKS_CRACKED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_slab_bricks_cracked")),
                WNBlocks.CONGLOMERATE_BRICKS_CRACKED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_slab_bricks_cracked")),
                WNBlocks.GNEISS_BRICKS_CRACKED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_slab_bricks_cracked")),
                WNBlocks.LIMESTONE_BRICKS_CRACKED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_slab_bricks_cracked")),
                WNBlocks.MARBLE_BRICKS_CRACKED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_slab_bricks_cracked")),
                WNBlocks.PEGMATITE_BRICKS_CRACKED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_slab_bricks_cracked")),
                WNBlocks.SLATE_BRICKS_CRACKED_SLAB = new SlabBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_slab_bricks_cracked")),




                WNBlocks.BASALT_STAIRS = new StairsBase(WNBlocks.BASALT_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_stairs")),
                WNBlocks.CONGLOMERATE_STAIRS = new StairsBase(WNBlocks.CONGLOMERATE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_stairs")),
                WNBlocks.GNEISS_STAIRS = new StairsBase(WNBlocks.GNEISS_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_stairs")),
                WNBlocks.LIMESTONE_STAIRS = new StairsBase(WNBlocks.LIMESTONE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_stairs")),
                WNBlocks.MARBLE_STAIRS = new StairsBase(WNBlocks.MARBLE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_stairs")),
                WNBlocks.PEGMATITE_STAIRS = new StairsBase(WNBlocks.PEGMATITE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_stairs")),
                WNBlocks.SLATE_STAIRS= new StairsBase(WNBlocks.SLATE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_stairs")),

                WNBlocks.BASALT_POLISHED_STAIRS = new StairsBase(WNBlocks.BASALT_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_polished_stairs")),
                WNBlocks.CONGLOMERATE_POLISHED_STAIRS = new StairsBase(WNBlocks.CONGLOMERATE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_polished_stairs")),
                WNBlocks.GNEISS_POLISHED_STAIRS = new StairsBase(WNBlocks.GNEISS_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_polished_stairs")),
                WNBlocks.LIMESTONE_POLISHED_STAIRS = new StairsBase(WNBlocks.LIMESTONE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_polished_stairs")),
                WNBlocks.MARBLE_POLISHED_STAIRS = new StairsBase(WNBlocks.MARBLE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_polished_stairs")),
                WNBlocks.PEGMATITE_POLISHED_STAIRS = new StairsBase(WNBlocks.PEGMATITE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_polished_stairs")),
                WNBlocks.SLATE_POLISHED_STAIRS= new StairsBase(WNBlocks.SLATE_ROCK.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_polished_stairs")),

                WNBlocks.BASALT_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_stairs_cobble")),
                WNBlocks.CONGLOMERATE_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_stairs_cobble")),
                WNBlocks.GNEISS_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_stairs_cobble")),
                WNBlocks.LIMESTONE_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_stairs_cobble")),
                WNBlocks.MARBLE_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_stairs_cobble")),
                WNBlocks.PEGMATITE_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_stairs_cobble")),
                WNBlocks.SLATE_COBBLE_STAIRS= new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_stairs_cobble")),

                WNBlocks.BASALT_MOSSY_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_stairs_cobble_mossy")),
                WNBlocks.CONGLOMERATE_MOSSY_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_stairs_cobble_mossy")),
                WNBlocks.GNEISS_MOSSY_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_stairs_cobble_mossy")),
                WNBlocks.LIMESTONE_MOSSY_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_stairs_cobble_mossy")),
                WNBlocks.MARBLE_MOSSY_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_stairs_cobble_mossy")),
                WNBlocks.PEGMATITE_MOSSY_COBBLE_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_stairs_cobble_mossy")),
                WNBlocks.SLATE_MOSSY_COBBLE_STAIRS= new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_stairs_cobble_mossy")),


                WNBlocks.BASALT_BRICKS_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_stairs_bricks")),
                WNBlocks.CONGLOMERATE_BRICKS_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_stairs_bricks")),
                WNBlocks.GNEISS_BRICKS_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_stairs_bricks")),
                WNBlocks.LIMESTONE_BRICKS_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_stairs_bricks")),
                WNBlocks.MARBLE_BRICKS_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_stairs_bricks")),
                WNBlocks.PEGMATITE_BRICKS_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_stairs_bricks")),
                WNBlocks.SLATE_BRICKS_STAIRS= new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_stairs_bricks")),

                WNBlocks.BASALT_BRICKS_MOSSY_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_stairs_bricks_mossy")),
                WNBlocks.CONGLOMERATE_BRICKS_MOSSY_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_stairs_bricks_mossy")),
                WNBlocks.GNEISS_BRICKS_MOSSY_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_stairs_bricks_mossy")),
                WNBlocks.LIMESTONE_BRICKS_MOSSY_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_stairs_bricks_mossy")),
                WNBlocks.MARBLE_BRICKS_MOSSY_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_stairs_bricks_mossy")),
                WNBlocks.PEGMATITE_BRICKS_MOSSY_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_stairs_bricks_mossy")),
                WNBlocks.SLATE_BRICKS_MOSSY_STAIRS= new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_stairs_bricks_mossy")),

                WNBlocks.BASALT_BRICKS_CHISELED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_stairs_bricks_chiseled")),
                WNBlocks.CONGLOMERATE_BRICKS_CHISELED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_stairs_bricks_chiseled")),
                WNBlocks.GNEISS_BRICKS_CHISELED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_stairs_bricks_chiseled")),
                WNBlocks.LIMESTONE_BRICKS_CHISELED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_stairs_bricks_chiseled")),
                WNBlocks.MARBLE_BRICKS_CHISELED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_stairs_bricks_chiseled")),
                WNBlocks.PEGMATITE_BRICKS_CHISELED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_stairs_bricks_chiseled")),
                WNBlocks.SLATE_BRICKS_CHISELED_STAIRS= new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_stairs_bricks_chiseled")),

                WNBlocks.BASALT_BRICKS_CRACKED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_stairs_bricks_cracked")),
                WNBlocks.CONGLOMERATE_BRICKS_CRACKED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_stairs_bricks_cracked")),
                WNBlocks.GNEISS_BRICKS_CRACKED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_stairs_bricks_cracked")),
                WNBlocks.LIMESTONE_BRICKS_CRACKED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_stairs_bricks_cracked")),
                WNBlocks.MARBLE_BRICKS_CRACKED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_stairs_bricks_cracked")),
                WNBlocks.PEGMATITE_BRICKS_CRACKED_STAIRS = new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_stairs_bricks_cracked")),
                WNBlocks.SLATE_BRICKS_CRACKED_STAIRS= new StairsBase(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_stairs_bricks_cracked")),



                WNBlocks.BASALT_BUTTON = new ButtonBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_button"),false),
                WNBlocks.CONGLOMERATE_BUTTON = new ButtonBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_button"),false),
                WNBlocks.GNEISS_BUTTON = new ButtonBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_button"),false),
                WNBlocks.LIMESTONE_BUTTON = new ButtonBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_button"),false),
                WNBlocks.MARBLE_BUTTON = new ButtonBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_button"),false),
                WNBlocks.PEGMATITE_BUTTON = new ButtonBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_button"),false),
                WNBlocks.SLATE_BUTTON= new ButtonBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_button"),false),

                WNBlocks.BASALT_PRESSURE_PLATE = new PressurePlateBase(PressurePlateBlock.Sensitivity.MOBS,Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_pressure_plate")),
                WNBlocks.CONGLOMERATE_PRESSURE_PLATE = new PressurePlateBase(PressurePlateBlock.Sensitivity.MOBS,Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_pressure_plate")),
                WNBlocks.GNEISS_PRESSURE_PLATE = new PressurePlateBase(PressurePlateBlock.Sensitivity.MOBS,Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_pressure_plate")),
                WNBlocks.LIMESTONE_PRESSURE_PLATE = new PressurePlateBase(PressurePlateBlock.Sensitivity.MOBS,Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_pressure_plate")),
                WNBlocks.MARBLE_PRESSURE_PLATE = new PressurePlateBase(PressurePlateBlock.Sensitivity.MOBS,Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_pressure_plate")),
                WNBlocks.PEGMATITE_PRESSURE_PLATE = new PressurePlateBase(PressurePlateBlock.Sensitivity.MOBS,Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_pressure_plate")),
                WNBlocks.SLATE_PRESSURE_PLATE= new PressurePlateBase(PressurePlateBlock.Sensitivity.MOBS,Block.Properties.create(Material.ROCK).hardnessAndResistance(0.5F, 1.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_pressure_plate")),


                WNBlocks.BASALT_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_wall")),
                WNBlocks.CONGLOMERATE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_wall")),
                WNBlocks.GNEISS_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_wall")),
                WNBlocks.LIMESTONE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_wall")),
                WNBlocks.MARBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_wall")),
                WNBlocks.PEGMATITE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_wall")),
                WNBlocks.SLATE_WALL= new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_wall")),

                WNBlocks.BASALT_POLISHED_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_polished_wall")),
                WNBlocks.CONGLOMERATE_POLISHED_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_polished_wall")),
                WNBlocks.GNEISS_POLISHED_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_polished_wall")),
                WNBlocks.LIMESTONE_POLISHED_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_polished_wall")),
                WNBlocks.MARBLE_POLISHED_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_polished_wall")),
                WNBlocks.PEGMATITE_POLISHED_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_polished_wall")),
                WNBlocks.SLATE_POLISHED_WALL= new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_polished_wall")),

                WNBlocks.BASALT_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_wall_cobble")),
                WNBlocks.CONGLOMERATE_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_wall_cobble")),
                WNBlocks.GNEISS_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_wall_cobble")),
                WNBlocks.LIMESTONE_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_wall_cobble")),
                WNBlocks.MARBLE_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_wall_cobble")),
                WNBlocks.PEGMATITE_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_wall_cobble")),
                WNBlocks.SLATE_COBBLE_WALL= new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_wall_cobble")),

                WNBlocks.BASALT_MOSSY_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_wall_cobble_mossy")),
                WNBlocks.CONGLOMERATE_MOSSY_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_wall_cobble_mossy")),
                WNBlocks.GNEISS_MOSSY_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_wall_cobble_mossy")),
                WNBlocks.LIMESTONE_MOSSY_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_wall_cobble_mossy")),
                WNBlocks.MARBLE_MOSSY_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_wall_cobble_mossy")),
                WNBlocks.PEGMATITE_MOSSY_COBBLE_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_wall_cobble_mossy")),
                WNBlocks.SLATE_MOSSY_COBBLE_WALL= new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_wall_cobble_mossy")),

                

                WNBlocks.BASALT_BRICKS_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_wall_bricks")),
                WNBlocks.CONGLOMERATE_BRICKS_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_wall_bricks")),
                WNBlocks.GNEISS_BRICKS_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_wall_bricks")),
                WNBlocks.LIMESTONE_BRICKS_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_wall_bricks")),
                WNBlocks.MARBLE_BRICKS_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_wall_bricks")),
                WNBlocks.PEGMATITE_BRICKS_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_wall_bricks")),
                WNBlocks.SLATE_BRICKS_WALL= new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_wall_bricks")),

                WNBlocks.BASALT_BRICKS_MOSSY_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_wall_bricks_mossy")),
                WNBlocks.CONGLOMERATE_BRICKS_MOSSY_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_wall_bricks_mossy")),
                WNBlocks.GNEISS_BRICKS_MOSSY_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_wall_bricks_mossy")),
                WNBlocks.LIMESTONE_BRICKS_MOSSY_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_wall_bricks_mossy")),
                WNBlocks.MARBLE_BRICKS_MOSSY_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_wall_bricks_mossy")),
                WNBlocks.PEGMATITE_BRICKS_MOSSY_WALL = new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_wall_bricks_mossy")),
                WNBlocks.SLATE_BRICKS_MOSSY_WALL= new WallBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_wall_bricks_mossy")),

                WNBlocks.BASALT_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_trapdoor")),
                WNBlocks.CONGLOMERATE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_trapdoor")),
                WNBlocks.GNEISS_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_trapdoor")),
                WNBlocks.LIMESTONE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_trapdoor")),
                WNBlocks.MARBLE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_trapdoor")),
                WNBlocks.PEGMATITE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_trapdoor")),
                WNBlocks.SLATE_TRAPDOOR= new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_trapdoor")),

                WNBlocks.BASALT_COBBLE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_cobble_trapdoor")),
                WNBlocks.CONGLOMERATE_COBBLE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_cobble_trapdoor")),
                WNBlocks.GNEISS_COBBLE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_cobble_trapdoor")),
                WNBlocks.LIMESTONE_COBBLE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_cobble_trapdoor")),
                WNBlocks.MARBLE_COBBLE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_cobble_trapdoor")),
                WNBlocks.PEGMATITE_COBBLE_TRAPDOOR = new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_cobble_trapdoor")),
                WNBlocks.SLATE_COBBLE_TRAPDOOR= new TrapDoorBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_cobble_trapdoor")),

                WNBlocks.BASALT_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_fence")),
                WNBlocks.CONGLOMERATE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_fence")),
                WNBlocks.GNEISS_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_fence")),
                WNBlocks.LIMESTONE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_fence")),
                WNBlocks.MARBLE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_fence")),
                WNBlocks.PEGMATITE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_fence")),
                WNBlocks.SLATE_FENCE= new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_fence")),

                WNBlocks.BASALT_COBBLE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("basalt_cobble_fence")),
                WNBlocks.CONGLOMERATE_COBBLE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("conglomerate_cobble_fence")),
                WNBlocks.GNEISS_COBBLE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("gneiss_cobble_fence")),
                WNBlocks.LIMESTONE_COBBLE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("limestone_cobble_fence")),
                WNBlocks.MARBLE_COBBLE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("marble_cobble_fence")),
                WNBlocks.PEGMATITE_COBBLE_FENCE = new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("pegmatite_cobble_fence")),
                WNBlocks.SLATE_COBBLE_FENCE= new FenceBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F),new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slate_cobble_fence")),

                WNBlocks.STICK_FRAME = new BlockBase(Block.Properties.create(Material.GLASS).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("stick_frame")),
                WNBlocks.BEAMS = new BlockBeams(Block.Properties.create(Material.GLASS).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("beams")),
                //WNBlocks.BRICKS_ARROWSLIT = new BlockArrowSlit(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("bricks_arrowslit")),
                //WNBlocks.BRICKS_MACHICOLATIONS = new BlockMachicolations(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("bricks_machicolations")),
                //WNBlocks.HALFARCH = new BlockHalfArch(Blocks.STONE.getDefaultState(),Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("halfarch")),
                WNBlocks.SLAB_CORNER = new BlockSlabCorner(Block.Properties.create(Material.GLASS).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slab_corner")),
                WNBlocks.SLAB_VERTICAL = new BlockSlabVertical(Block.Properties.create(Material.GLASS).hardnessAndResistance(1.5F, 6.0F), new Item.Properties().group(Main.WILDNATURE_BUILDING_GROUP), Main.RegistryEvents.location("slab_vertical")),


        };
    }

    public Block[] getRocks() {
        return rocks;
    }
}
